agieval_en:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0

aime24:
  n: 16
  max_new_tokens: 4096
  temperature: 0.7
  top_p: 1.0

aime25:
  n: 16
  max_new_tokens: 4096
  temperature: 0.7
  top_p: 1.0

gpqa_diamond:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0

humaneval_plus:
  n: 16
  max_new_tokens: 4096
  temperature: 0.2
  top_p: 0.95

ifbench:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0

ifeval:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0

livecodebench:
  n: 16
  max_new_tokens: 4096
  temperature: 0.2
  top_p: 0.95

mmlu_pro:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0

zebralogic:
  n: 1
  max_new_tokens: 4096
  temperature: 0.0
  top_p: 1.0
